import data from "../../data/poop.json";

/** Generated by `bun run words` — see scripts/build-words.ts. */
export const TARGET = data.target;
export const STARTS = data.starts.split(",");

const DISTANCE = new Map<string, number>();
const FREQUENCY = new Map<string, number>();
for (const line of data.words.split("\n")) {
  const [word, dist, count] = line.split(",");
  DISTANCE.set(word!, Number(dist));
  FREQUENCY.set(word!, Number(count));
}

export const isWord = (w: string) => DISTANCE.has(w);

/** Shortest number of guesses from `w` to the target. */
export const distanceToTarget = (w: string) => DISTANCE.get(w) ?? Infinity;

export function isOneLetterApart(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) diff++;
  return diff === 1;
}

function neighbors(word: string): string[] {
  const out: string[] = [];
  for (let i = 0; i < word.length; i++) {
    for (let c = 97; c <= 122; c++) {
      const w = word.slice(0, i) + String.fromCharCode(c) + word.slice(i + 1);
      if (w !== word && DISTANCE.has(w)) out.push(w);
    }
  }
  return out;
}

export interface Solution {
  /** Number of distinct shortest paths. */
  count: number;
  /** The shortest path made of the most common words (start and target included). */
  best: string[];
}

/**
 * Walks the shortest-path DAG towards the target: from each word only neighbors exactly
 * one step closer qualify. The showcased path maximises the summed log
 * frequency, so it favours everyday words.
 */
export function solve(start: string): Solution {
  const memo = new Map<string, { count: number; score: number; path: string[] }>();
  const visit = (w: string): { count: number; score: number; path: string[] } => {
    const cached = memo.get(w);
    if (cached) return cached;
    const own = Math.log(FREQUENCY.get(w) ?? 1);
    let result = { count: 1, score: own, path: [w] };
    if (w !== TARGET) {
      const d = distanceToTarget(w);
      let count = 0;
      let bestNext: { score: number; path: string[] } | null = null;
      for (const n of neighbors(w)) {
        if (distanceToTarget(n) !== d - 1) continue;
        const sub = visit(n);
        count += sub.count;
        if (!bestNext || sub.score > bestNext.score) bestNext = sub;
      }
      result = { count, score: own + (bestNext?.score ?? 0), path: [w, ...(bestNext?.path ?? [])] };
    }
    memo.set(w, result);
    return result;
  };
  const { count, path } = visit(start);
  return { count, best: path };
}
