import data from "../../data/five-letter.json";

/** Generated by `bun run words` — see scripts/build-words.ts. */
export const ANSWERS = data.answers.split(",");
const GUESSES = new Set(data.guesses.split(","));

export const isWord = (w: string) => GUESSES.has(w);

export type Mark = "correct" | "present" | "absent";

/** Standard scoring, handling repeated letters: exact hits first, then the rest. */
export function evaluate(guess: string, answer: string): Mark[] {
  const marks: Mark[] = Array(guess.length).fill("absent");
  const unmatched = new Map<string, number>();
  for (let i = 0; i < guess.length; i++) {
    if (guess[i] === answer[i]) marks[i] = "correct";
    else unmatched.set(answer[i]!, (unmatched.get(answer[i]!) ?? 0) + 1);
  }
  for (let i = 0; i < guess.length; i++) {
    const left = unmatched.get(guess[i]!) ?? 0;
    if (marks[i] !== "correct" && left > 0) {
      marks[i] = "present";
      unmatched.set(guess[i]!, left - 1);
    }
  }
  return marks;
}
