import data from "../../data/500.json";
import { evaluate } from "../five-letter/words";

export { isWord } from "../five-letter/words";

/** Generated by `bun run words` — see scripts/build-words.ts. */
export const ANSWERS = data.answers.split(",");

/** Letters that never appear in an answer; the keyboard greys them out from the start. */
export const RARE_LETTERS = ["q", "j", "x", "z"];

export interface Score {
  /** Right letter in the right spot. */
  green: number;
  /** In the word, but in another spot. */
  yellow: number;
  /** Not in the word (or more copies than the word has). */
  red: number;
}

/**
 * How many letters of the guess are green, yellow and red. Unlike the five-letter game the
 * player only sees these totals, never which letter is which.
 */
export function score(guess: string, answer: string): Score {
  const marks = evaluate(guess, answer);
  const count = (m: string) => marks.filter(x => x === m).length;
  return { green: count("correct"), yellow: count("present"), red: count("absent") };
}
